version: 0.0
os: linux

files:
  - source: ./my-app-1.0-SNAPSHOT.jar
    destination: /tmp

hooks:
  ApplicationStop:
    - location: scripts/server-stop.sh
      timeout: 20
  ApplicationStart:
    - location: scripts/server-start.sh
      timeout: 20